/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisteminformasisiswa.siswa;

import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.lang.String;
import java.text.ParseException;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

import sisteminformasisiswa.MainMenu;
import sisteminformasisiswa.konekDB;

/**
 *
 * @author aris
 */

public class DataSiswa extends javax.swing.JPanel {

    /**
     * Creates new form DataSiswa
     */
    Statement stm;
    ResultSet RsUser;
    String userBaru="";
    String userSiswa="";
    SimpleDateFormat formatTanggal = new SimpleDateFormat("d-MMMM-yyyy");
    String tanggal="";
    
    public DataSiswa() {
        initComponents();
        Calendar cal = Calendar.getInstance();
        tanggal = formatTanggal.format(cal.getTime());
        
        namaSekolah.setText("SMA NEGERI 1 LASKAR PELANGI ");
        loadData(userBaru);
        this.lblTanggal.setText(tanggal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnNilaiSiswa = new javax.swing.JButton();
        btnDataDiri = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNama = new javax.swing.JLabel();
        PanelSiswa = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        namaSekolah = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 255));
        setMaximumSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        BtnNilaiSiswa.setBackground(new java.awt.Color(255, 255, 255));
        BtnNilaiSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisteminformasisiswa/icon/applications-education.png"))); // NOI18N
        BtnNilaiSiswa.setText("LIHAT NILAI");
        BtnNilaiSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNilaiSiswaActionPerformed(evt);
            }
        });

        btnDataDiri.setBackground(new java.awt.Color(255, 255, 255));
        btnDataDiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisteminformasisiswa/icon/gnome-session-switch.png"))); // NOI18N
        btnDataDiri.setText("DATA DIRI");
        btnDataDiri.setBorder(null);
        btnDataDiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataDiriActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));

        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        lblNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNama.setText("NAMA SISWA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(lblNama)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNilaiSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDataDiri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnDataDiri, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnNilaiSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );

        javax.swing.GroupLayout PanelSiswaLayout = new javax.swing.GroupLayout(PanelSiswa);
        PanelSiswa.setLayout(PanelSiswaLayout);
        PanelSiswaLayout.setHorizontalGroup(
            PanelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelSiswaLayout.setVerticalGroup(
            PanelSiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));

        namaSekolah.setForeground(new java.awt.Color(255, 255, 255));
        namaSekolah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaSekolah.setText("Nama Sekolah");

        jPanel4.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        lblTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lblTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTanggal.setText("Tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(lblTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSiswa)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelSiswa)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void dataDiri() throws ParseException
    {
        DataDiriSiswa diri = new DataDiriSiswa();
        NilaiSiswa n = new NilaiSiswa();
        diri.loadData(userSiswa);
        diri.setBounds(0,0,1062, 566);
        PanelSiswa.remove(n);
        PanelSiswa.removeAll();
        PanelSiswa.add(diri);
        diri.setVisible(true);

        
    }
    private void btnDataDiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataDiriActionPerformed
        try {
            dataDiri();
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDataDiriActionPerformed
    public void nilai() throws ParseException
    {
        NilaiSiswa n = new NilaiSiswa();
        DataDiriSiswa diri = new DataDiriSiswa();
        n.loadData(userSiswa);
        n.setBounds(0,0,1065, 566);
        PanelSiswa.remove(diri);
        PanelSiswa.removeAll();
        PanelSiswa.add(n);
        
        n.setVisible(true);
        
        
    }
    private void BtnNilaiSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNilaiSiswaActionPerformed
        try {
            nilai();
        } catch (ParseException ex) {
            Logger.getLogger(DataSiswa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnNilaiSiswaActionPerformed
    
    public void loadData(String userBaru)
    {
        
        try
        {
        String namaSiswa = new String(userBaru);
        Connection con = konekDB.koneksi();
        stm = con.createStatement();
        RsUser = stm.executeQuery("select * from d_siswa where nis='"+namaSiswa+"'");
        userSiswa = userBaru;
        //String ss = RsUser.toString();
        //txtNama.setText(ss);
        
        while(RsUser.next())
                {
                    lblNama.setText("Hei, "+RsUser.getString("nm_siswa").toUpperCase());
                    
                }         
        }catch(SQLException error)
        {
            JOptionPane.showMessageDialog(null,error);
        }
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNilaiSiswa;
    private javax.swing.JDesktopPane PanelSiswa;
    private javax.swing.JButton btnDataDiri;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel namaSekolah;
    // End of variables declaration//GEN-END:variables
}
