/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisteminformasisiswa;

import sisteminformasisiswa.admin.DataAdmin;
import sisteminformasisiswa.guru.DataGuru;
import sisteminformasisiswa.siswa.DataSiswa;
import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JScrollPane;


/**
 *
 * @author aris
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */

    Connection con;
    ResultSet RsUser;
    Statement stm;
    //JComboBox comboPilih;

    public MainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JDesktopPane();
        PanelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPanduan = new javax.swing.JButton();
        comboPilih = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelSekolah = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMA Negeri 1 Laskar Pelangi");
        setResizable(false);

        PanelUtama.setBackground(new java.awt.Color(0, 0, 255));
        PanelUtama.setMaximumSize(new java.awt.Dimension(1366, 768));

        PanelLogin.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setText("User");

        jLabel3.setText("Password");

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisteminformasisiswa/icon/path6884.png"))); // NOI18N
        btnLogin.setText("MASUK");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisteminformasisiswa/icon/system-shutdown.png"))); // NOI18N
        btnCancel.setText("BATAL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPanduan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisteminformasisiswa/icon/applications-other.png"))); // NOI18N
        btnPanduan.setText("PANDUAN LOGIN");
        btnPanduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanduanActionPerformed(evt);
            }
        });

        comboPilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Siswa", "Guru" }));
        comboPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPilihActionPerformed(evt);
            }
        });

        jLabel4.setText("Sebagai");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sisteminformasisiswa/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPanduan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(40, 40, 40)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPanduan)
                .addContainerGap())
        );

        labelSekolah.setFont(new java.awt.Font("Ubuntu Light", 1, 36)); // NOI18N
        labelSekolah.setForeground(new java.awt.Color(255, 255, 255));
        labelSekolah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSekolah.setText("SMA NEGERI 1 LASKAR PELANGI");

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSekolah, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(498, 498, 498)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUtamaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelSekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelUtama.setLayer(PanelLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelUtama.setLayer(labelSekolah, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        mnLogout.setIcon(new javax.swing.ImageIcon("/home/aris/ICON/system-shutdown.png")); // NOI18N
        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanduanActionPerformed
        Panduan p = new Panduan();
        p.setVisible(true);
    }//GEN-LAST:event_btnPanduanActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void comboPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPilihActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        try
        {
            PanelUtama.removeAll();
            MainMenu logout = new MainMenu();
            logout.setVisible(true);
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mnLogoutActionPerformed
    
    private void login()
    {
        try
        {
            Connection con = konekDB.koneksi();
            char[] input = jPasswordField1.getPassword();
            String pass = new String(jPasswordField1.getPassword());
            stm = con.createStatement();
            String sis = "Siswa";
            String guru = "Guru";
            String admin = "Admin";
            
            if(comboPilih.getSelectedItem().equals(sis))
            {
                RsUser = stm.executeQuery("select * from d_siswa \n" +
                "inner join user \n" +
                "on user.nis = d_siswa.nis \n" +
                "where user.id_user='"+txtUser.getText()+"' and user.pass='"+pass+"'");
                String userSiswa = new String(txtUser.getText());
                int baris=0;
                    while(RsUser.next())
                {
                    baris = RsUser.getRow();
                }
                    if (baris==1)
                        {
         
                        DataSiswa siswa = new DataSiswa();
                        siswa.loadData(userSiswa);
                        siswa.setBounds(0,0,1300, 659);
                        PanelUtama.add(siswa);
                        siswa.setVisible(true);
                        PanelLogin.show(false);
                        labelSekolah.show(false);
                        }
                    else
                        {
                            JOptionPane.showMessageDialog(null, "User dan Password Siswa Tidak Cocok ");
                        }
            }
            else if(comboPilih.getSelectedItem().equals(admin))
            {
                RsUser = stm.executeQuery("select * from admin where id_admin='"+txtUser.getText()+"' and "
                                        + "pass_admin='"+pass+"'");
                String userAdmin = new String(txtUser.getText());
                
                int baris=0;
                    while(RsUser.next())
                {
                    baris = RsUser.getRow();
                }
                    if (baris==1)
                        {
                        DataAdmin adm = new DataAdmin();
                        adm.setBounds(0,0,1300, 659);
                        PanelUtama.add(adm);
                        adm.setVisible(true);
                        PanelLogin.show(false);
                        labelSekolah.show(false);
                        }
                    else
                        {
                            JOptionPane.showMessageDialog(null, "User Admin dan Password Tidak Cocok ");
                        }
                
                
            }
            else if(comboPilih.getSelectedItem().equals(admin))
            {
                RsUser = stm.executeQuery("select * from admin where id_admin='"+txtUser.getText()+"' and "
                                        + "pass_admin='"+pass+"'");
                String userAdmin = new String(txtUser.getText());
                
                int baris=0;
                    while(RsUser.next())
                {
                    baris = RsUser.getRow();
                }
                    if (baris==1)
                        {
                        DataAdmin adm = new DataAdmin();
                        adm.setBounds(0,0,1300, 659);
                        PanelUtama.add(adm);
                        adm.setVisible(true);
                        PanelLogin.show(false);
                        labelSekolah.show(false);
                        }
                    else
                        {
                            JOptionPane.showMessageDialog(null, "User Admin dan Password Tidak Cocok ");
                        }
                
                
            }
            else if(comboPilih.getSelectedItem().equals(guru))
            {
                RsUser = stm.executeQuery("select * from tb_guru\n" +
                                            "inner join usr_guru\n" +
                                            "on usr_guru.nip = tb_guru.nip\n" +
                                            "where tb_guru.nip='"+txtUser.getText()+"';");
                String userAdmin = new String(txtUser.getText());
                
                int baris=0;
                    while(RsUser.next())
                {
                    baris = RsUser.getRow();
                }
                    if (baris==1)
                        {
                        DataGuru gur = new DataGuru();
                        gur.loadData(userAdmin);
                        gur.setBounds(0,0,1300, 659);
                        PanelUtama.add(gur);
                        gur.setVisible(true);
                        PanelLogin.show(false);
                        labelSekolah.show(false);
                        }
                    else
                        {
                            JOptionPane.showMessageDialog(null, "User Admin dan Password Tidak Cocok ");
                        }
                
                
            }
            
            
         
        }catch(Exception error)
        {
            JOptionPane.showMessageDialog(null,"Login Error");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JDesktopPane PanelUtama;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPanduan;
    private javax.swing.JComboBox comboPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel labelSekolah;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
